// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_documents-upload_document
 */
export type Body_documents_upload_document = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Message
     */
    message: string;
};

/**
 * ConversationPublic
 */
export type ConversationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type: string;
    /**
     * Document Id
     */
    document_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentPublic
 */
export type DocumentPublic = {
    /**
     * Filename
     */
    filename: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * File Type
     */
    file_type: string;
    /**
     * File Size Bytes
     */
    file_size_bytes?: number;
    /**
     * Status
     */
    status?: string;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Qdrant Collection
     */
    qdrant_collection?: string;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FeedbackRequest
 */
export type FeedbackRequest = {
    /**
     * Rating
     */
    rating: string;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MessagePublic
 */
export type MessagePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sources
     */
    sources: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Intent
     */
    intent: string | null;
    /**
     * Model Used
     */
    model_used: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * QuizPublic
 */
export type QuizPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Question Count
     */
    question_count: number;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Message
 */
export type app__models__conversation__Message = {
    /**
     * Id
     */
    id?: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sources
     */
    sources?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Intent
     */
    intent?: string | null;
    /**
     * Model Used
     */
    model_used?: string | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * Message
 */
export type app__models__core__Message = {
    /**
     * Message
     */
    message: string;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: app__models__core__Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: app__models__core__Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: app__models__conversation__Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: app__models__conversation__Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: app__models__conversation__Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type profileReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me';
};

export type profileReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type profileReadUserMeResponse = profileReadUserMeResponses[keyof profileReadUserMeResponses];

export type profileUpdateUserMeData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me';
};

export type profileUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type profileUpdateUserMeError = profileUpdateUserMeErrors[keyof profileUpdateUserMeErrors];

export type profileUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type profileUpdateUserMeResponse = profileUpdateUserMeResponses[keyof profileUpdateUserMeResponses];

export type profileUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/profile/me/password';
};

export type profileUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type profileUpdatePasswordMeError = profileUpdatePasswordMeErrors[keyof profileUpdatePasswordMeErrors];

export type profileUpdatePasswordMeResponses = {
    /**
     * Response Profile-Update Password Me
     *
     * Successful Response
     */
    200: unknown;
};

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: app__models__core__Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: app__models__core__Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type documentsReadDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/';
};

export type documentsReadDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentsError = documentsReadDocumentsErrors[keyof documentsReadDocumentsErrors];

export type documentsReadDocumentsResponses = {
    /**
     * Response Documents-Read Documents
     *
     * Successful Response
     */
    200: Array<DocumentPublic>;
};

export type documentsReadDocumentsResponse = documentsReadDocumentsResponses[keyof documentsReadDocumentsResponses];

export type documentsUploadDocumentData = {
    body: Body_documents_upload_document;
    path?: never;
    query?: never;
    url: '/api/v1/documents/';
};

export type documentsUploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsUploadDocumentError = documentsUploadDocumentErrors[keyof documentsUploadDocumentErrors];

export type documentsUploadDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsUploadDocumentResponse = documentsUploadDocumentResponses[keyof documentsUploadDocumentResponses];

export type documentsDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/documents/{id}';
};

export type documentsDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsDeleteDocumentError = documentsDeleteDocumentErrors[keyof documentsDeleteDocumentErrors];

export type documentsDeleteDocumentResponses = {
    /**
     * Response Documents-Delete Document
     *
     * Successful Response
     */
    200: unknown;
};

export type documentsReadDocumentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/documents/{id}';
};

export type documentsReadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type documentsReadDocumentError = documentsReadDocumentErrors[keyof documentsReadDocumentErrors];

export type documentsReadDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type documentsReadDocumentResponse = documentsReadDocumentResponses[keyof documentsReadDocumentResponses];

export type chatStreamChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/stream';
};

export type chatStreamChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatStreamChatError = chatStreamChatErrors[keyof chatStreamChatErrors];

export type chatStreamChatResponses = {
    /**
     * Response Chat-Stream Chat
     *
     * Successful Response
     */
    200: unknown;
};

export type chatGetConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/chat/conversations';
};

export type chatGetConversationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatGetConversationsError = chatGetConversationsErrors[keyof chatGetConversationsErrors];

export type chatGetConversationsResponses = {
    /**
     * Response Chat-Get Conversations
     *
     * Successful Response
     */
    200: Array<ConversationPublic>;
};

export type chatGetConversationsResponse = chatGetConversationsResponses[keyof chatGetConversationsResponses];

export type chatGetMessagesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{id}/messages';
};

export type chatGetMessagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatGetMessagesError = chatGetMessagesErrors[keyof chatGetMessagesErrors];

export type chatGetMessagesResponses = {
    /**
     * Response Chat-Get Messages
     *
     * Successful Response
     */
    200: Array<MessagePublic>;
};

export type chatGetMessagesResponse = chatGetMessagesResponses[keyof chatGetMessagesResponses];

export type chatSubmitFeedbackData = {
    body: FeedbackRequest;
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/v1/chat/messages/{message_id}/feedback';
};

export type chatSubmitFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatSubmitFeedbackError = chatSubmitFeedbackErrors[keyof chatSubmitFeedbackErrors];

export type chatSubmitFeedbackResponses = {
    /**
     * Response Chat-Submit Feedback
     *
     * Successful Response
     */
    200: unknown;
};

export type quizGenerateQuizData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Document Id
         */
        document_id: string;
    };
    url: '/api/v1/quiz/generate';
};

export type quizGenerateQuizErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type quizGenerateQuizError = quizGenerateQuizErrors[keyof quizGenerateQuizErrors];

export type quizGenerateQuizResponses = {
    /**
     * Successful Response
     */
    200: QuizPublic;
};

export type quizGenerateQuizResponse = quizGenerateQuizResponses[keyof quizGenerateQuizResponses];

export type quizListQuizzesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/quiz/';
};

export type quizListQuizzesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type quizListQuizzesError = quizListQuizzesErrors[keyof quizListQuizzesErrors];

export type quizListQuizzesResponses = {
    /**
     * Response Quiz-List Quizzes
     *
     * Successful Response
     */
    200: Array<QuizPublic>;
};

export type quizListQuizzesResponse = quizListQuizzesResponses[keyof quizListQuizzesResponses];

export type adminCheckHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/health';
};

export type adminCheckHealthResponses = {
    /**
     * Response Admin-Check Health
     *
     * Successful Response
     */
    200: unknown;
};

export type adminGetFeedbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Rating
         */
        rating?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/feedback';
};

export type adminGetFeedbackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetFeedbackError = adminGetFeedbackErrors[keyof adminGetFeedbackErrors];

export type adminGetFeedbackResponses = {
    /**
     * Response Admin-Get Feedback
     *
     * Successful Response
     */
    200: unknown;
};

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];

export type AIModelConfigPublic = {
    id: string;
    name: string;
    provider: string;
    model_id: string;
    base_url?: string | null;
    is_active: boolean;
    is_embedding: boolean;
    created_at: string;
};

export type AIModelConfigCreate = {
    name: string;
    provider: string;
    model_id: string;
    base_url?: string | null;
    api_key?: string | null;
    is_active?: boolean;
    is_embedding?: boolean;
};

export type SystemPromptPublic = {
    id: string;
    name: string;
    content: string;
    is_active: boolean;
    created_at: string;
};

export type SystemPromptCreate = {
    name: string;
    content: string;
    is_active?: boolean;
};

export type adminAiReadModelsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/admin/ai/models';
};

export type adminAiReadModelsResponses = {
    200: Array<AIModelConfigPublic>;
};

export type adminAiCreateModelData = {
    body: AIModelConfigCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/ai/models';
};

export type adminAiCreateModelResponses = {
    200: AIModelConfigPublic;
};

export type adminAiDeleteModelData = {
    body?: never;
    path: {
        model_id: string;
    };
    query?: never;
    url: '/api/v1/admin/ai/models/{model_id}';
};

export type adminAiDeleteModelResponses = {
    200: { message: string };
};

export type adminAiReadPromptsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/admin/ai/prompts';
};

export type adminAiReadPromptsResponses = {
    200: Array<SystemPromptPublic>;
};

export type adminAiCreatePromptData = {
    body: SystemPromptCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/ai/prompts';
};

export type adminAiCreatePromptResponses = {
    200: SystemPromptPublic;
};

export type adminAiDeletePromptData = {
    body?: never;
    path: {
        prompt_id: string;
    };
    query?: never;
    url: '/api/v1/admin/ai/prompts/{prompt_id}';
};

export type adminAiDeletePromptResponses = {
    200: { message: string };
};

export type QuestionPublic = {
    id: string;
    order_index: number;
    question_text: string;
    options: Record<string, string>;
    correct_answer: string;
    explanation?: string | null;
};

export type quizGetQuizData = {
    body?: never;
    path: {
        quiz_id: string;
    };
    query?: never;
    url: '/api/v1/quiz/{quiz_id}';
};

export type quizGetQuizResponses = {
    200: QuizPublic;
};

export type quizGetQuizQuestionsData = {
    body?: never;
    path: {
        quiz_id: string;
    };
    query?: never;
    url: '/api/v1/quiz/{quiz_id}/questions';
};

export type quizGetQuizQuestionsResponses = {
    200: Array<QuestionPublic>;
};
