"""verify_schema_sync

Revision ID: 479a20bac371
Revises: 7302cade1ed8
Create Date: 2026-09-02 09:21:03.841535

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '479a20bac371'
down_revision = '7302cade1ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aimodelconfig', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('aimodelconfig', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('aimodelconfig', 'api_key')
    op.alter_column('document', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'study'::character varying"))
    op.alter_column('document', 'folder',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'Chung'::character varying"))
    op.drop_constraint(op.f('message_quiz_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'quiz', ['quiz_id'], ['id'])
    op.alter_column('quiz', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_quiz_id_fkey'), 'message', 'quiz', ['quiz_id'], ['id'], ondelete='SET NULL')
    op.alter_column('document', 'folder',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'Chung'::character varying"))
    op.alter_column('document', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'study'::character varying"))
    op.add_column('aimodelconfig', sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('aimodelconfig', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('aimodelconfig', 'api_key_encrypted',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
